---
- name: Testing andrewrothstein.powershell (trust, modules)
  hosts: all
  vars:
    powershell_trust:
      - Name: PSGallery
        InstallationPolicy: Trusted
    powershell_install_modules:
      - Name: Az
        Scope: CurrentUser
  roles:
    - role: '{{ playbook_dir }}'
- name: Testing andrewrothstein.powershell (default)
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'pwsh -version'
      ansible.builtin.command: /usr/local/bin/pwsh -version
      changed_when: false
      register: powershell_output
    - name: Output of 'pwsh -version'
      ansible.builtin.debug:
        msg: '{{ powershell_output.stdout }}'
